### ISSUE TITLE
Wrong status recognition

### ISSUE THREAD

**Issue by TimsManter** [bajcmartinez/nordvpn-status#3]
It seems like the extension is reading whatever `nordvpn status` command is writing to stdout and interprets the first line as a connection status. Because for now the Arch Linux package is out of date the status command is displaying notification about update as first line which makes connection recognition fail.

```sh
$ nordvpn status  
A new version of NordVPN is available! Please update the application.
Status: Connected
(...)
```
![image](https://user-images.githubusercontent.com/5507688/59379863-06aab500-8d58-11e9-9802-5567ff4cf990.png)

**Comment by jcmartinezdev** [comment]
Sorry for the late reply I was moving to a new country and have been pretty off for a while. I'll work on a solution for that problem. I wasn't aware of that particular issue, I'll make it so the recognition is a bit smarter than just the first line

**Comment by jcmartinezdev** [comment]
I don't have that version thing now to really test it, but I included changes that would fix the problem. If you manually installed the extension just replace the file extension.js and it will work. If you installed it through the gnome-extensions website, give it a few days until the team approves it and deploy it to your desktop.
