### ISSUE TITLE
Menu item replicated multiple times

### ISSUE THREAD

**Issue by mmnaseri** [bajcmartinez/nordvpn-status#5]
Hi,

Thanks for the great extension. I am running Arch Linux with 3.34.1. For some reason, this extension's menu item is replicated. I am not sure what the trigger for this replication is, but after a while, a new replica (fully functioning, with status updates and all) will be added.

![Screenshot from 2019-11-19 10-55-10](https://user-images.githubusercontent.com/543672/69177108-cb0cd780-0abb-11ea-9e77-cdcb65e55d94.png)

Do you need any additional information from me?

**Comment by ghost** [comment]
Getting the same issue on the latest Fedora 31 (GNOME 3.34.2).

**Comment by hausofwong** [comment]
Also having the same issues on Manjaro (GNOME 3.34.2) & Arch (GNOME 3.34.3).

It was working fine on 'version 2' of the extension. Soon as I updated the to the latest version (4) the repeating menu item occurred.

**Comment by kevgilmore** [comment]
Having the same issue on ubuntu 18.04. Also the menu icon fails to show most of the time for me, however in the menu the nordvpn item (both) say connected.

**Comment by jcmartinezdev** [comment]
Fixed! new version available soon!
