### ISSUE TITLE
some ideas

### ISSUE THREAD

**Issue by drandreaskrueger** [bajcmartinez/nordvpn-status#6]
First of all - thanks a lot. This is very useful.

I am learning about gnome-shell and extensions at the moment, and I noticed that your extension clutters the `journalctl | grep gnome-shell |  tail -n 100` with a lot of lines just stating `Updating NordVPN Status...` every 30 seconds I believe.

What about:

* let us decide how many seconds / minutes apart.
* IF logging (perhaps even make that optional) give the _result_ of the update, i.e. what exactly could you find out about the nordvpn connection, and log _that_
* make it into a version which is not in the (wifi, bluetooth, battery, ...) menu, but at top level. For now I am using [this argos script](https://github.com/brecke/bitbar-vpn-flag) for the display, but I cannot connect/disconnect there.

Thanks a lot, keep up the good work!

**Comment by jcmartinezdev** [comment]
Hi, sorry for the very late reply here. I'll work on it!
