### ISSUE TITLE
after update from 18.04 to 20.04 the extension has an exclamation mark and cannot be launched

### ISSUE THREAD

**Issue by petr-hybler** [bajcmartinez/nordvpn-status#7]
Hi, I recently updated to 20.04 and cannot actually make the extension work again ... 

![Screenshot from 2020-04-22 12-45-10](https://user-images.githubusercontent.com/17429498/79941537-1f671980-8497-11ea-8aee-1804c10222bc.png)

I don't even see anything while hovering over the exclamation mark :( 

OS Model: Ubuntu 20.04 LTS (x64)
Gnome: 3.36.1
Kernel: Linux version 5.4.0-26-generic (buildd@lcy01-amd64-029) (gcc version 9.3.0 (Ubuntu 9.3.0-10ubuntu2))

**Comment by petr-hybler** [comment]
I made it work somehow but the layout is odd ... 

![Screenshot from 2020-04-22 22-07-16](https://user-images.githubusercontent.com/17429498/79992164-bfe42a80-84e5-11ea-96b8-08578f550226.png)
![Screenshot from 2020-04-22 22-07-29](https://user-images.githubusercontent.com/17429498/79992187-c377b180-84e5-11ea-8a0c-7adba6cf0031.png)

+ when connected there is no DISCONNECT 
![Screenshot from 2020-04-22 22-07-46](https://user-images.githubusercontent.com/17429498/79992286-ddb18f80-84e5-11ea-8a6e-650b29b9b6dd.png)

**Comment by Bicet** [comment]
I have the same behviour on gnome 3.36-1 on arch :)

**Comment by jcmartinezdev** [comment]
Working on it now

**Comment by jcmartinezdev** [comment]
I fixed the issue, it usually takes a few days until someone from gnome approves the update to the plugin.

**Comment by petr-hybler** [comment]
thx.. I already migrated to another extension which I find more user friendly.. anyway - thx :)

**Comment by jcmartinezdev** [comment]
cool, mind sharing? I built this one as the others were not so good

**Comment by petr-hybler** [comment]
sure .. this one ...  

https://extensions.gnome.org/extension/1595/nordvpn-connect/

in 20.04 works fine :)
